version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Zipping Lambda function..."
      - zip function.zip lambda_function.py
  post_build:
    commands:
      - echo "Updating Lambda function..."
      - aws lambda update-function-code --function-name MyTestLambda --zip-file fileb://function.zip

artifacts:
  files:
    - function.zip
